name: Grand Tag Test
on:
  push:
    branches:
      - master
jobs:
  when-tag:
    name: Runs when its a tag
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Echo yay
        run: echo YES!

  when-no-tag:
    name: Runs when its not a tag
    runs-on: ubuntu-latest

    if: "!startsWith(github.ref, 'refs/tags/')"

    steps:
      - name: 'Echo no tag :shrug:'
        run: echo well here is no tag, uh-uh!
