name: Grand Tag Test
on:
  push:
    branches:
      - master
jobs:
  itself:
    name: Itself
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo (needed for building anyway, but we also get to know if we're tagged)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Some common prep haha
        run: echo this is prep

      - name: Check if this is a tag
        id: tag-check
        run: git describe --exact-match HEAD && echo '::set-output name=TAGGED::1' || true

      - name: when is tag
        run: echo THERE IS A TAG
        if: steps.tag-check.outputs.TAGGED

      - name: when no tag
        run: echo GIT RELEASE HAHAHA
        if: '!steps.tag-check.outputs.TAGGED'
