name: Update Changelog
on:
  - push
jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout the wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Extract changelog
        uses: ./extract-changelog
        with:
          root-commit: 3554

      - name: Render changelog
        uses: ./render-changelog
        with:
          date-format: 1%F
          changelog-template: .github/workflows/changelog-template.md
          filename: wiki/Changelog.md

      - name: Push to wiki
        run: |
          cd wiki
          git config --local user.email action@github.com
          git config --local user.name 'Changelog Updater'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update changelog'
          git push

