name: Update Changelog
on:
  - push
jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Set up Python dependencies
        run: python -m pip install pyyaml

      - name: Checkout the main repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout the wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Generate changelog
        run: python .github/scripts/extract-changelog.py | tee changelog.yml

      - name: Render changelog
        run: cat changelog.yml | python .github/scripts/render-changelog.py | tee wiki/Changelog.md

      - name: Push to wiki
        run: |
          cd wiki
          git config --local user.email action@github.com
          git config --local user.name 'Changelog Updater'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update changelog'
          git push

